name: comicslate
description: A new Flutter project.

version: 1.0.3+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0
  http: ^0.12.0
  shared_preferences: ^0.5.2
  built_value: ^6.4.0
  flutter_advanced_networkimage: ^0.5.0
  webview_flutter: ^0.3.5+4
  flutter_cache_manager: ^1.1.3
  share: ^0.6.0
  quiver: '>=2.0.0 <3.0.0'

  firebase_analytics: ^2.1.1
  firebase_crashlytics: ^0.0.4
  package_info: ^0.4.0
  url_launcher: ^5.0.1
  device_info: ^0.4.0
  provide: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^6.4.0
  build_runner: ^1.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: DatFestComic
      fonts:
      - asset: fonts/dat_fest.ttf

  assets:
    - images/logo0.webp
    - images/logo1.webp
    - images/logo2.webp
    - images/logo3.webp
    - images/logo4.webp
    - images/logo5.webp
    - images/logo6.webp
    - images/logo7.webp
    - images/logo8.webp
    - images/favicon.webp
