name: comicslate
description: Official client application for https://comicslate.org/

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0
  http: ^0.12.0
  shared_preferences: ^0.5.4
  built_value: ^6.8.2
  flutter_advanced_networkimage: ^0.5.0
  webview_flutter: ^0.3.15
  flutter_cache_manager: ^1.1.3
  share: ^0.6.3
  quiver: ">=2.0.0 <3.0.0"

  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.0
  package_info: ^0.4.0
  url_launcher: ^5.2.5
  device_info: ^0.4.1
  provide: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^6.8.2
  build_runner:
  test: ^1.6.2

flutter:
  uses-material-design: true

  fonts:
    - family: DatFestComic
      fonts:
        - asset: fonts/dat_fest.ttf

  assets:
    - images/logo0.webp
    - images/logo1.webp
    - images/logo2.webp
    - images/logo3.webp
    - images/logo4.webp
    - images/logo5.webp
    - images/logo6.webp
    - images/logo7.webp
    - images/logo8.webp
    - images/favicon.webp

builders:
  built_value_generator: any
