name: comicslate
description: Official client application for https://comicslate.org/

# Version information is set by Fastlane when building:
# $ flutter build --build-name=... --build-number=...
# We set a default here for debugging purposes because debug binary is not
# usually built via Fastlane.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl:
  http:
  shared_preferences:
  built_value:
  flutter_advanced_networkimage:
  flutter_cache_manager:
  share:
  quiver:
  wakelock:
  firebase_analytics:
  package_info:
  url_launcher:
  device_info:
  provide:
  flutter_sentry:

dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator:
  build_runner:
  test:

flutter:
  uses-material-design: true

  fonts:
    - family: DatFestComic
      fonts:
        - asset: fonts/dat_fest.ttf

  assets:
    - images/logo0.webp
    - images/logo1.webp
    - images/logo2.webp
    - images/logo3.webp
    - images/logo4.webp
    - images/logo5.webp
    - images/logo6.webp
    - images/logo7.webp
    - images/logo8.webp
    - images/favicon.webp
